### ISSUE TITLE
plugin breaks font-type pad settings

### ISSUE THREAD

**Issue by T-Mike** [samirsayyad/ep_full_hyperlinks#7]
When I install the plugin, changing font-type doesn't work anymore. (in the UI, "Pad Settings" -> "font-type")

Works when disabling this line on firefox dev tools :
https://github.com/samirsayyad/ep_full_hyperlinks/blob/48e24d112a2e7e4184d4d94279447f0e6808a882/static/css/link.css#L1-L3

**Comment by samirsayyad** [comment]
Hi , 
Thanks for reporting I will check asap

**Comment by samirsayyad** [comment]
Fixed, sorry about late.

**Comment by T-Mike** [comment]
np thanks !
